plugins:
  - jest
  - import

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  object-curly-newline: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]